### All users
GET http://localhost:3000/api/users

### One user by uuid
GET http://localhost:3000/api/users/QC6_A3m8RT

# npx nanoid -s 10

### Find users with name
GET http://localhost:3000/api/users?name=adam
